### ISSUE TITLE
メンバー参加時にメンバー情報をDBに書き込む処理

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.CodeWarehouse#111]
# 要件
1. メンバーテーブルを最新化する一括処理
1. メンバー参加時にDBにメンバー情報を書き込む処理

**Comment by supleiades** [comment]
## テストメンバー参加前
```sql
| 471 | 603582455756095488 | 801336569944473610 | とりたをち                    | 2021-01-20 06:38:42 |          1 | 2021-06-21 23:20:59 | 2021-06-21 23:20:59 |
| 472 | 603582455756095488 | 438564206246232064 | ゆい                          | 2021-04-29 06:43:37 |          1 | 2021-06-21 23:20:59 | 2021-06-21 23:20:59 |
| 473 | 603582455756095488 | 689449857672282158 | Osa                           | 2020-04-29 00:43:34 |          1 | 2021-06-21 23:20:59 | 2021-06-21 23:20:59 |
| 474 | 603582455756095488 | 580404320386678784 | okaken                        | 2020-08-09 13:42:07 |          1 | 2021-06-21 23:20:59 | 2021-06-21 23:20:59 |
+-----+--------------------+--------------------+-------------------------------+---------------------+------------+---------------------+---------------------+
158 rows in set (0.00 sec)
```

## テストメンバー参加後
 ```sql
 | 945 | 603582455756095488 | 801336569944473610 | とりたをち                    | 2021-01-20 06:38:42 |          1 | 2021-06-21 23:31:23 | 2021-06-21 23:31:23 |
| 946 | 603582455756095488 | 438564206246232064 | ゆい                          | 2021-04-29 06:43:37 |          1 | 2021-06-21 23:31:23 | 2021-06-21 23:31:23 |
| 947 | 603582455756095488 | 689449857672282158 | Osa                           | 2020-04-29 00:43:34 |          1 | 2021-06-21 23:31:23 | 2021-06-21 23:31:23 |
| 948 | 603582455756095488 | 580404320386678784 | okaken                        | 2020-08-09 13:42:07 |          1 | 2021-06-21 23:31:23 | 2021-06-21 23:31:23 |
| 949 | 603582455756095488 | 186844273029677056 | KeiitiChan                    | 2021-06-21 14:53:31 |          1 | 2021-06-21 23:53:32 | 2021-06-21 23:53:32 |
+-----+--------------------+--------------------+-------------------------------+---------------------+------------+---------------------+---------------------+
159 rows in set (0.00 sec)
```

## テストメンバー脱退後
- エラー
```sh
Traceback (most recent call last):
  File "/home/centos/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/staging/discord.CodeWarehouse/Cogs/Managements/joinLeaveLog.py", line 65, in on_member_remove
    session.query(Studymembers).filter(Studymembers.member_id==member.id).first().delete()
TypeError: delete() missing 1 required positional argument: 'session'
```
- 修正後
```sql
| 945 | 603582455756095488 | 801336569944473610 | とりたをち                    | 2021-01-20 06:38:42 |          1 | 2021-06-21 23:31:23 | 2021-06-21 23:31:23 |
| 946 | 603582455756095488 | 438564206246232064 | ゆい                          | 2021-04-29 06:43:37 |          1 | 2021-06-21 23:31:23 | 2021-06-21 23:31:23 |
| 947 | 603582455756095488 | 689449857672282158 | Osa                           | 2020-04-29 00:43:34 |          1 | 2021-06-21 23:31:23 | 2021-06-21 23:31:23 |
| 948 | 603582455756095488 | 580404320386678784 | okaken                        | 2020-08-09 13:42:07 |          1 | 2021-06-21 23:31:23 | 2021-06-21 23:31:23 |
+-----+--------------------+--------------------+-------------------------------+---------------------+------------+---------------------+---------------------+
158 rows in set (0.00 sec)
```

**Comment by supleiades** [comment]
## DBの情報が書き換えられてなくて週間集計に記録が出力されていなかった件
- 問題の集計結果
```
今日の日付：2021-06-21
先週の日付：2021-06-14〜06-20
====================
Name：keita higaki
　勉強した曜日：月,火,水,木,金,土,日
　合計勉強時間：87時間47分
====================
Name：こまごめピペット
　勉強した曜日：月,火,x,木,x,土,日
　合計勉強時間：31時間5分
====================
Name：HAL
　勉強した曜日：月,火,水,木,x,土,日
　合計勉強時間：15時間45分
====================
Name：Osa
　勉強した曜日：月,火,x,x,金,土,x
　合計勉強時間：7時間13分
====================
Name：noria
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：6時間47分
====================
Name：ろぐなな
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：6時間1分
====================
Name：いわまさ
　勉強した曜日：月,x,x,x,金,土,x
　合計勉強時間：5時間1分
====================
Name：むらせ
　勉強した曜日：月,火,x,x,x,土,x
　合計勉強時間：4時間49分
====================
Name：SuPleiades
　勉強した曜日：x,火,x,x,x,x,x
　合計勉強時間：4時間21分
====================
Name：なしぶる
　勉強した曜日：月,x,水,x,x,x,日
　合計勉強時間：4時間3分
====================
Name：夜な夜なスタディ
　勉強した曜日：月,火,x,x,x,x,x
　合計勉強時間：3時間33分
====================
Name：shin
　勉強した曜日：月,火,水,x,x,x,x
　合計勉強時間：3時間22分
====================
Name：jun kubotamai@まいじゅん
　勉強した曜日：x,x,x,x,x,土,x
　合計勉強時間：3時間13分
====================
Name：nakayumc
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：3時間7分
====================
Name：チートん
　勉強した曜日：x,火,x,x,x,x,x
　合計勉強時間：2時間44分
====================
Name：misa
　勉強した曜日：x,x,水,木,金,土,x
　合計勉強時間：2時間3分
====================
Name：yuuty
　勉強した曜日：x,x,x,x,x,土,日
　合計勉強時間：2時間2分
====================
Name：toshi123
　勉強した曜日：x,x,x,x,x,土,x
　合計勉強時間：1時間42分
====================
Name：bana
　勉強した曜日：月,火,水,x,x,x,x
　合計勉強時間：1時間39分
====================
Name：hima_zin
　勉強した曜日：x,火,水,x,x,x,x
　合計勉強時間：1時間36分
====================
Name：藍鉄
　勉強した曜日：x,x,x,x,金,土,x
　合計勉強時間：1時間35分
====================
Name：よくわからない人
　勉強した曜日：x,火,水,x,x,x,x
　合計勉強時間：1時間25分
====================
Name：みやとり
　勉強した曜日：x,火,x,x,金,x,x
　合計勉強時間：0時間53分
====================
Name：ervitis
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：0時間44分
====================
Name：はるまき
　勉強した曜日：x,火,x,x,x,x,x
　合計勉強時間：0時間36分
====================
Name：シコルノスキー
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：0時間33分
====================
Name：たこ
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：0時間32分
====================
Name：みや
　勉強した曜日：x,火,x,x,x,x,x
　合計勉強時間：0時間31分
====================
Name：リョウタ
　勉強した曜日：x,火,x,x,x,x,x
　合計勉強時間：0時間21分
====================
Name：ニコ先輩
　勉強した曜日：x,x,x,x,x,土,x
　合計勉強時間：0時間10分
====================
Name：二宮
　勉強した曜日：月,x,x,x,x,x,x
　合計勉強時間：0時間7分
　```

- 修正後
```
今日の日付：2021-06-22
先週の日付：2021-06-14〜06-20
====================
Name：keita higaki
　勉強した曜日：月,火,水,木,金,土,日
　合計勉強時間：87時間47分
====================
Name：こまごめピペット
　勉強した曜日：月,火,x,木,x,土,日
　合計勉強時間：31時間5分
====================
Name：HAL
　勉強した曜日：月,火,水,木,x,土,日
　合計勉強時間：15時間45分
====================
Name：Osa
　勉強した曜日：月,火,x,x,金,土,x
　合計勉強時間：7時間13分
====================
Name：noria
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：6時間47分
====================
Name：ろぐなな
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：6時間1分
====================
Name：caz
　勉強した曜日：x,x,x,木,金,土,日
　合計勉強時間：5時間38分
====================
Name：いわまさ
　勉強した曜日：月,x,x,x,金,土,x
　合計勉強時間：5時間1分
====================
Name：むらせ
　勉強した曜日：月,火,x,x,x,土,x
　合計勉強時間：4時間49分
====================
Name：SuPleiades
　勉強した曜日：x,火,x,x,x,x,x
　合計勉強時間：4時間21分
====================
Name：なしぶる
　勉強した曜日：月,x,水,x,x,x,日
　合計勉強時間：4時間3分
====================
Name：夜な夜なスタディ
　勉強した曜日：月,火,x,x,x,x,x
　合計勉強時間：3時間33分
====================
Name：shin
　勉強した曜日：月,火,水,x,x,x,x
　合計勉強時間：3時間22分
====================
Name：jun kubotamai@まいじゅん
　勉強した曜日：x,x,x,x,x,土,x
　合計勉強時間：3時間13分
====================
Name：nakayumc
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：3時間7分
====================
Name：チートん
　勉強した曜日：x,火,x,x,x,x,x
　合計勉強時間：2時間44分
====================
Name：みさ
　勉強した曜日：x,x,水,木,金,土,x
　合計勉強時間：2時間3分
====================
Name：yuuty
　勉強した曜日：x,x,x,x,x,土,日
　合計勉強時間：2時間2分
====================
Name：toshi123
　勉強した曜日：x,x,x,x,x,土,x
　合計勉強時間：1時間42分
====================
Name：bana
　勉強した曜日：月,火,水,x,x,x,x
　合計勉強時間：1時間39分
====================
Name：hima_zin
　勉強した曜日：x,火,水,x,x,x,x
　合計勉強時間：1時間36分
====================
Name：藍鉄
　勉強した曜日：x,x,x,x,金,土,x
　合計勉強時間：1時間35分
====================
Name：よくわからない人
　勉強した曜日：x,火,水,x,x,x,x
　合計勉強時間：1時間25分
====================
Name：みやとり
　勉強した曜日：x,火,x,x,金,x,x
　合計勉強時間：0時間53分
====================
Name：maikeru(召)
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：0時間50分
====================
Name：ervitis
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：0時間44分
====================
Name：はるまき
　勉強した曜日：x,火,x,x,x,x,x
　合計勉強時間：0時間36分
====================
Name：シコルノスキー
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：0時間33分
====================
Name：たこ
　勉強した曜日：x,x,x,x,x,x,日
　合計勉強時間：0時間32分
====================
Name：みや
　勉強した曜日：x,火,x,x,x,x,x
　合計勉強時間：0時間31分
====================
Name：リョウタ
　勉強した曜日：x,火,x,x,x,x,x
　合計勉強時間：0時間21分
====================
Name：ｺｳﾀ8龔
　勉強した曜日：月,x,x,x,x,x,x
　合計勉強時間：0時間12分
====================
Name：ニコ先輩
　勉強した曜日：x,x,x,x,x,土,x
　合計勉強時間：0時間10分
====================
Name：二宮
　勉強した曜日：月,x,x,x,x,x,x
　合計勉強時間：0時間7分
　```

**Comment by supleiades** [comment]
- 検証結果は想定通り
- 以下はログ

## 参加時に古いデータがもしも存在していた場合
-  joined_dtと名前が最新かされるようにしている
```sql
mysql> select * from studymembers where member_id=186844273029677056;
+------+--------------------+--------------------+-------------+---------------------+------------+---------------------+---------------------+
| id   | guild_id           | member_id          | member_name | joined_dt           | enrollment | created_at          | updated_at          |
+------+--------------------+--------------------+-------------+---------------------+------------+---------------------+---------------------+
| 1109 | 603582455756095488 | 186844273029677056 | KeiitiChan  | 2021-06-22 14:48:16 |          1 | 2021-06-22 23:48:17 | 2021-06-22 23:48:17 |
+------+--------------------+--------------------+-------------+---------------------+------------+---------------------+---------------------+
1 row in set (0.00 sec)

mysql> select * from studymembers where member_id=186844273029677056;
+------+--------------------+--------------------+-------------+---------------------+------------+---------------------+---------------------+
| id   | guild_id           | member_id          | member_name | joined_dt           | enrollment | created_at          | updated_at          |
+------+--------------------+--------------------+-------------+---------------------+------------+---------------------+---------------------+
| 1109 | 603582455756095488 | 186844273029677056 | KeiitiChan  | 2021-06-22 15:05:49 |          1 | 2021-06-22 23:48:17 | 2021-06-23 00:05:49 |
+------+--------------------+--------------------+-------------+---------------------+------------+---------------------+---------------------+
1 row in set (0.00 sec)
```

## 離脱した時
- enrollmentをFalseにする
```
mysql> select * from studymembers where member_id=186844273029677056;
+------+--------------------+--------------------+-------------+---------------------+------------+---------------------+---------------------+
| id   | guild_id           | member_id          | member_name | joined_dt           | enrollment | created_at          | updated_at          |
+------+--------------------+--------------------+-------------+---------------------+------------+---------------------+---------------------+
| 1109 | 603582455756095488 | 186844273029677056 | KeiitiChan  | 2021-06-22 15:05:49 |          1 | 2021-06-22 23:48:17 | 2021-06-23 00:05:49 |
+------+--------------------+--------------------+-------------+---------------------+------------+---------------------+---------------------+
1 row in set (0.00 sec)

mysql> mysql> select * from studymembers where member_id=186844273029677056;
+------+--------------------+--------------------+-------------+---------------------+------------+---------------------+---------------------+
| id   | guild_id           | member_id          | member_name | joined_dt           | enrollment | created_at          | updated_at          |
+------+--------------------+--------------------+-------------+---------------------+------------+---------------------+---------------------+
| 1109 | 603582455756095488 | 186844273029677056 | KeiitiChan  | 2021-06-22 15:05:49 |          0 | 2021-06-22 23:48:17 | 2021-06-23 00:12:58 |
+------+--------------------+--------------------+-------------+---------------------+------------+---------------------+---------------------+
1 row in set (0.00 sec)
```
