### ISSUE TITLE
言語ロール付与処理の起動時のエラー：embed_field20個上限オーバー問題

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.CodeWarehouse#115]
```py
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/Cogs/Managements/rolesmanager.py", line 37, in on_raw_reaction_add
    if payload.member.bot:
AttributeError: 'NoneType' object has no attribute 'bot'
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/Cogs/Managements/view_TimesChannel.py", line 27, in on_raw_reaction_add
    if payload.member.bot:
AttributeError: 'NoneType' object has no attribute 'bot'
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/Cogs/Managements/rolesmanager.py", line 37, in on_raw_reaction_add
    if payload.member.bot:
AttributeError: 'NoneType' object has no attribute 'bot'
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/Cogs/Managements/view_TimesChannel.py", line 27, in on_raw_reaction_add
    if payload.member.bot:
AttributeError: 'NoneType' object has no attribute 'bot'
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/Cogs/Managements/languageVisualization.py", line 40, in on_ready
    await self.message.add_reaction(languages["emoji"])
  File "/home/centos/repos/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/message.py", line 1149, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "/home/centos/repos/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 30010): Maximum number of reactions reached (20)
```

**Comment by supleiades** [comment]
チケットが重複しているためクローズ
また、一部は本日修正済み
