### ISSUE TITLE
自己紹介用のDBテーブル作成とコードをDB連携したものに修正

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.CodeWarehouse#124]
# 対象コード
https://github.com/mo9mo9study/discord.CodeWarehouse/blob/master/Cogs/Managements/selfIntroduction.py

# 内容
- 自己紹介用のテーブル作成
- 既存ユーザーの自己紹介データをDBにデータ移行
- コードを自己紹介用のギルドに追加・修正する処理をDB用で挿入・修正する処理に変更

**Comment by supleiades** [comment]
@iceE-1591 にDEBUGサーバーの自己紹介データをcsv（カンマ区切り）でファイルに保存する処理を作成依頼した

**Comment by supleiades** [comment]
私のタスク
・テーブルをsqlalchemy経由で作成
・テストデータを入れる
・既存コードをテストデータを使って自己紹介を操作できるコードにリファクタリングする
・csvデータをデータベースに入れ込む
・本番コード切り替え

**Comment by supleiades** [comment]
現状のまま一旦動かしてみた
```py
例外が発生しました: OperationalError
(pymysql.err.OperationalError) (1054, "Unknown column 'sendmsg_id' in 'field list'")
[SQL: INSERT INTO selfintroduction (guild_id, member_id, nickname, sex, twitter_id, specialty, before_study, after_study, sendmsg_id, mod_column, created_at, updated_at) VALUES (%(guild_id)s, %(member_id)s, %(nickname)s, %(sex)s, %(twitter_id)s, %(specialty)s, %(before_study)s, %(after_study)s, %(sendmsg_id)s, %(mod_column)s, %(created_at)s, %(updated_at)s)]
[parameters: {'guild_id': 696268022930866177, 'member_id': 186844273029677056, 'nickname': None, 'sex': None, 'twitter_id': None, 'specialty': None, 'before_study': None, 'after_study': None, 'sendmsg_id': None, 'mod_column': None, 'created_at': datetime.datetime(2021, 11, 15, 23, 42, 33, 185700), 'updated_at': datetime.datetime(2021, 11, 15, 23, 42, 33, 185728)}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

The above exception was the direct cause of the following exception:

  File "/home/centos/work/discord.CodeWarehouse/Cogs/Managements/selfIntroduction.py", line 64, in db_insert_selfintroduction
    Selfintroduction.insert(obj)
  File "/home/centos/work/discord.CodeWarehouse/Cogs/Managements/selfIntroduction.py", line 76, in on_member_join
    await self.db_insert_selfintroduction(member)
  File "/home/centos/work/discord.CodeWarehouse/tmp-run.py", line 18, in <module>
    bot.run(TOKEN)
```

**Comment by supleiades** [comment]
- 特定のカラムが作成される前の自作パッケージを使用していたので、
` pip install -U -i https://test.pypi.org/simple/ mo9mo9db`でアップデート後
- テーブル再作成

```py
>>> from sqlalchemy.ext.declarative import declarative_base
>>> Base = declarative_base()
>>> from mo9mo9db.dbsession import get_db_engine
>>> engine = get_db_engine()
>>> Selfintroduction.__table__.drop(engine)
>>> Selfintroduction.__table__.create(engine)
```

**Comment by supleiades** [comment]
```py
例外が発生しました: TypeError
'NoneType' object is not subscriptable
  File "/home/centos/work/discord.CodeWarehouse/Cogs/Managements/selfIntroduction.py", line 153, in check_missingdata
    if not member_data["nickname"]:
  File "/home/centos/work/discord.CodeWarehouse/Cogs/Managements/selfIntroduction.py", line 483, in on_message
    missingdata_column, next_missingdata_column = self.check_missingdata(
  File "/home/centos/work/discord.CodeWarehouse/tmp-run.py", line 18, in <module>
    bot.run(TOKEN)
    ```

**Comment by supleiades** [comment]
- 一方その頃のDBは
```sql
mysql> select * from selfintroduction;
+----+--------------------+--------------------+----------+------+------------+-----------+--------------+-------------+------------+------------+---------------------+---------------------+
| id | guild_id           | member_id          | nickname | sex  | twitter_id | specialty | before_study | after_study | sendmsg_id | mod_column | created_at          | updated_at          |
+----+--------------------+--------------------+----------+------+------------+-----------+--------------+-------------+------------+------------+---------------------+---------------------+
|  1 | 696268022930866177 | 186844273029677056 | NULL     | NULL | NULL       | NULL      | NULL         | NULL        | NULL       | NULL       | 2021-11-15 23:54:16 | 2021-11-15 23:54:16 |
+----+--------------------+--------------------+----------+------+------------+-----------+--------------+-------------+------------+------------+---------------------+---------------------+
```

**Comment by supleiades** [comment]
変数でカラムを指定したい場合
```py
```py
obj = Selfintroduction.objects(session).filter(Selfintroduction.member_id == "186844273029677056").first()

>>> vars(obj)
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7f99c631c4c0>, 'created_at': datetime.datetime(2021, 11, 15, 23, 54, 16), 'sendmsg_id': None, 'after_study': None, 'specialty': None, 'sex': None, 'member_id': '186844273029677056', 'id': 1, 'updated_at': datetime.datetime(2021, 11, 15, 23, 54, 16), 'mod_column': None, 'before_study': None, 'twitter_id': None, 'nickname': 'aaaa', 'guild_id': '696268022930866177'}

l = ["member_id", "nickname"]
for s in l:
    print(obj.__dict__[s])
```

**Comment by supleiades** [comment]
```py
例外が発生しました: IntegrityError
(pymysql.err.IntegrityError) (1062, "Duplicate entry '186844273029677056' for key 'selfintroduction.member_id'")
[SQL: INSERT INTO selfintroduction (guild_id, member_id, nickname, sex, twitter_id, specialty, before_study, after_study, sendmsg_id, mod_column, created_at, updated_at) VALUES (%(guild_id)s, %(member_id)s, %(nickname)s, %(sex)s, %(twitter_id)s, %(specialty)s, %(before_study)s, %(after_study)s, %(sendmsg_id)s, %(mod_column)s, %(created_at)s, %(updated_at)s)]
[parameters: {'guild_id': 696268022930866177, 'member_id': 186844273029677056, 'nickname': None, 'sex': None, 'twitter_id': None, 'specialty': None, 'before_study': None, 'after_study': None, 'sendmsg_id': None, 'mod_column': None, 'created_at': datetime.datetime(2021, 11, 16, 0, 32, 50, 773011), 'updated_at': datetime.datetime(2021, 11, 16, 0, 32, 50, 773044)}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

The above exception was the direct cause of the following exception:

  File "/home/centos/work/discord.CodeWarehouse/Cogs/Managements/selfIntroduction.py", line 64, in db_insert_selfintroduction
    Selfintroduction.insert(obj)
  File "/home/centos/work/discord.CodeWarehouse/Cogs/Managements/selfIntroduction.py", line 76, in on_member_join
    await self.db_insert_selfintroduction(member)
  File "/home/centos/work/discord.CodeWarehouse/tmp-run.py", line 18, in <module>
    bot.run(TOKEN)
```

**Comment by supleiades** [comment]
自己紹介を送信前の段階
```sql
mysql> select * from selfintroduction;
+----+--------------------+--------------------+----------+------+------------+--------------+--------------+--------------+------------+------------+---------------------+---------------------+
| id | guild_id           | member_id          | nickname | sex  | twitter_id | specialty    | before_study | after_study  | sendmsg_id | mod_column | created_at          | updated_at          |
+----+--------------------+--------------------+----------+------+------------+--------------+--------------+--------------+------------+------------+---------------------+---------------------+
|  1 | 696268022930866177 | 186844273029677056 | けい     | 男   | なし       | テスト１     | テスト２     | テスト３     | NULL       | sendmsg_id | 2021-11-15 23:54:16 | 2021-11-21 15:41:03 |
+----+--------------------+--------------------+----------+------+------------+--------------+--------------+--------------+------------+------------+---------------------+---------------------+
```
自己紹介送信済み
```sql
mysql> select * from selfintroduction;
+----+--------------------+--------------------+----------+------+------------+--------------+--------------+--------------+--------------------+------------+---------------------+---------------------+
| id | guild_id           | member_id          | nickname | sex  | twitter_id | specialty    | before_study | after_study  | sendmsg_id         | mod_column | created_at          | updated_at          |
+----+--------------------+--------------------+----------+------+------------+--------------+--------------+--------------+--------------------+------------+---------------------+---------------------+
|  1 | 696268022930866177 | 186844273029677056 | けい     | 男   | なし       | テスト１     | テスト２     | テスト３     | 911877636215697440 | NULL       | 2021-11-15 23:54:16 | 2021-11-21 16:16:11 |
+----+--------------------+--------------------+----------+------+------------+--------------+--------------+--------------+--------------------+------------+---------------------+---------------------+
1 row in set (0.00 sec)
```

**Comment by supleiades** [comment]
DMで¥preditとメッセージ送信後
```py
Ignoring exception in command predit:
Traceback (most recent call last):
  File "/home/centos/work/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/centos/work/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/centos/work/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 789, in prepare
    await self._parse_arguments(ctx)
  File "/home/centos/work/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 697, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "/home/centos/work/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 542, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: message is a required argument that is missing.
```

**Comment by supleiades** [comment]
¥preditで自己紹介更新してみる
![image](https://user-images.githubusercontent.com/45380191/142755223-aa932b96-e99e-4772-b628-2ed242f22bd9.png)

```sql
mysql> select * from selfintroduction;
+----+--------------------+--------------------+----------+-----------+------------+--------------+--------------+--------------+--------------------+------------+---------------------+---------------------+
| id | guild_id           | member_id          | nickname | sex       | twitter_id | specialty    | before_study | after_study  | sendmsg_id         | mod_column | created_at          | updated_at          |
+----+--------------------+--------------------+----------+-----------+------------+--------------+--------------+--------------+--------------------+------------+---------------------+---------------------+
|  1 | 696268022930866177 | 186844273029677056 | けー     | 非公開    | なし       | テスト１     | テスト２     | テスト３     | 911896155917529128 | NULL       | 2021-11-15 23:54:16 | 2021-11-21 17:29:46 |
+----+--------------------+--------------------+----------+-----------+------------+--------------+--------------+--------------+--------------------+------------+---------------------+---------------------+
1 row in set (0.00 sec)

mysql> select * from selfintroduction;
+----+--------------------+--------------------+----------+------+------------+--------------+--------------+--------------+--------------------+------------+---------------------+---------------------+
| id | guild_id           | member_id          | nickname | sex  | twitter_id | specialty    | before_study | after_study  | sendmsg_id         | mod_column | created_at          | updated_at          |
+----+--------------------+--------------------+----------+------+------------+--------------+--------------+--------------+--------------------+------------+---------------------+---------------------+
|  1 | 696268022930866177 | 186844273029677056 | けー     | 女   | なし       | テスト１     | テスト２     | テスト３     | 911896459018903582 | NULL       | 2021-11-15 23:54:16 | 2021-11-21 17:30:58 |
+----+--------------------+--------------------+----------+------+------------+--------------+--------------+--------------+--------------------+------------+---------------------+---------------------+
1 row in set (0.00 sec)
```

更新後のメッセージがピンク枠になっていることを確認
![image](https://user-images.githubusercontent.com/45380191/142755249-ed777ce3-cb61-4fa7-8b32-d0bbbf4a657c.png)

**Comment by supleiades** [comment]
中二つのメッセージが不要だね
![image](https://user-images.githubusercontent.com/45380191/144146160-7acc39a0-bb8f-4ccd-a70e-cb779fb30487.png)

**Comment by supleiades** [comment]
¥preditとコマンドを打って自己紹介をしようとすると
on_messageとcommandのどちらもが動いてしまう

![image](https://user-images.githubusercontent.com/45380191/144747352-51369e9c-1b83-4998-8609-c3e933d49f26.png)

なので、on_message側にはpreditで動作しないようにする

**Comment by supleiades** [comment]
- まだ自己紹介を送信していない状態でギルドに参加＋メッセージ送信した場合
```sql
mysql> SELECT * FROM selfintroduction WHERE member_id=186844273029677056;
+--------------------+--------------------+----------+--------+------------+-----------+--------------+-------------+------------+------------+---------------------+---------------------+
| guild_id           | member_id          | nickname | gender | twitter_id | specialty | before_study | after_study | sendmsg_id | mod_column | created_at          | updated_at          |
+--------------------+--------------------+----------+--------+------------+-----------+--------------+-------------+------------+------------+---------------------+---------------------+
| 696268022930866177 | 186844273029677056 | けー     | 男     | ai         | u         | え           | おお        | NULL       | NULL       | 2021-12-05 18:23:39 | 2021-12-06 00:08:45 |
+--------------------+--------------------+----------+--------+------------+-----------+--------------+-------------+------------+------------+---------------------+---------------------+
1 row in set (0.00 sec)
```

**Comment by supleiades** [comment]
- 参加後、いつもの「いらっしゃいません」と「名前は？」を聞かれるが、既存データがある場合入力した名前を無視して、既存データでテンプレートを作り、送信の可否を確認される（まあ、いいだろう）
![image](https://user-images.githubusercontent.com/45380191/144752376-2c82022e-af2e-4333-b2b6-61fc207d42f4.png)
```sql
mysql> SELECT * FROM selfintroduction WHERE member_id=186844273029677056;
+--------------------+--------------------+----------+--------+------------+-----------+--------------+-------------+--------------------+------------+---------------------+---------------------+
| guild_id           | member_id          | nickname | gender | twitter_id | specialty | before_study | after_study | sendmsg_id         | mod_column | created_at          | updated_at          |
+--------------------+--------------------+----------+--------+------------+-----------+--------------+-------------+--------------------+------------+---------------------+---------------------+
| 696268022930866177 | 186844273029677056 | けー     | 男     | ai         | u         | え           | おお        | 917071093708234772 | NULL       | 2021-12-05 18:23:39 | 2021-12-06 00:13:08 |
+--------------------+--------------------+----------+--------+------------+-----------+--------------+-------------+--------------------+------------+---------------------+---------------------+
```
