### ISSUE TITLE
ボイスチャンネル参加すると見えるようになるチャンネルの閲覧用権限付与処理のデバックが邪魔すぎる問題

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.CodeWarehouse#128]
- うまく動かなかった当時にデバックとして、がむしゃらに書き残した遺産であるprintコードを削除して綺麗にしよう！
![image](https://user-images.githubusercontent.com/45380191/133956311-a89790d5-acad-4186-8969-42966a0e75af.png)

**Comment by supleiades** [comment]
# マージ前の確認
- ラウンジ入退室時
```sh
$ python3 management.py
--------------------
起動中...
BOT NAME : プールの監視員
BOT ID : 618077392686153742
--------------------
[INFO] SuPleiadesがラウンジ�に入室
[INFO] SuPleiadesに権限「only_musicbotChat」を付与
[INFO] SuPleiadesに権限「only_loungeChat」を付与
[INFO] SuPleiadesがラウンジ�から退室
[INFO] SuPleiadesから権限「only_musicbotChat」を剥奪
[INFO] SuPleiadesから権限「only_workingroomChat」を剥奪
[INFO] SuPleiadesから権限「only_loungeChat」を剥奪
```
- 作業部屋の入退室時
```sh
[INFO] SuPleiadesが作業部屋（記録無）に入室
[INFO] SuPleiadesに権限「only_musicbotChat」を付与
[INFO] SuPleiadesに権限「only_workingroomChat」を付与
[INFO] SuPleiadesが作業部屋（記録無）から退室
[INFO] SuPleiadesから権限「only_musicbotChat」を剥奪
[INFO] SuPleiadesから権限「only_workingroomChat」を剥奪
[INFO] SuPleiadesから権限「only_loungeChat」を剥奪
```

**Comment by supleiades** [comment]
```
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/centos/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/staging/discord.CodeWarehouse/Cogs/Managements/voiceChannelJoinLeave_roleModify.py", line 20, in on_voice_state_update
    if after.channel.id == self.workRoomVoiceChatId:
AttributeError: 'Reaction_AddRole' object has no attribute 'workRoomVoiceChatId'
```


その修正後確認したのは、このファイルは「
https://github.com/mo9mo9study/discord.CodeWarehouse/blob/master/Cogs/Managements/rolesmanager.py
」
このファイルから読み込まれているため、そしてそのファイルから読み込まれた際にdiscordのイベントが動いているようだ
＝voiceChannelJoinLeave_roleModify.pyをコメントして動かないようにしていてもエラーが起きてしまっている

**Comment by supleiades** [comment]
rolemanagement
読み込まれている部分の繋がりをなくして、動作確認する

**Comment by supleiades** [comment]
付与、剥奪どちらも想定通りに動いていることを確認
```
[INFO] SuPleiadesがラウンジ🔈から退室
[DEBUG] <class 'discord.member.Member'>
[INFO] SuPleiadesから権限「only_musicbotChat」を剥奪
[DEBUG] <class 'discord.member.Member'>
[INFO] SuPleiadesから権限「only_workingroomChat」を剥奪
[DEBUG] <class 'discord.member.Member'>
[INFO] SuPleiadesから権限「only_loungeChat」を剥奪
[INFO] SuPleiadesがラウンジ🔈に入室
[DEBUG] <class 'discord.member.Member'>
[INFO] SuPleiadesに権限「only_musicbotChat」を付与
[DEBUG] <class 'discord.member.Member'>
[INFO] SuPleiadesに権限「only_loungeChat」を付与
[DEBUG] <class 'discord.member.Member'>
[INFO] SuPleiadesに権限「JOIN_gym」を付与
```
