### ISSUE TITLE
自己紹介用のDMメッセージが送信されてこない問題

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.CodeWarehouse#153]

**Comment by supleiades** [comment]
```py
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/Cogs/Managements/selfIntroduction.py", line 48, in on_member_join
    await self.DEBUG_GUILD.create_text_channel(str(member.id))
  File "/home/centos/repos/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/guild.py", line 948, in create_text_channel
    data = await self._create_channel(name, overwrites, ChannelType.text, category, reason=reason, **options)
  File "/home/centos/repos/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 30013): Maximum number of server channels reached (500)
```

**Comment by supleiades** [comment]
チャンネル数が500個超えたって話
問題だよって話、はよDB連携しろよって話
