### ISSUE TITLE
勉強机自動作成の処理のエラー

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.CodeWarehouse#160]
```py
[DEBUG] member: 9 / channel: 9
[DEBUG] 勉強机10以降が存在しません
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/Cogs/Managements/create_studydesk.py", line 168, in on_voice_state_update
    await self.create_studydesk(member)
  File "/home/centos/repos/discord.CodeWarehouse/Cogs/Managements/create_studydesk.py", line 138, in create_studydesk
    lastvc_pos = vc_sorted_dict[len(
KeyError: 10
```

**Comment by supleiades** [comment]
「勉強机を作成する」というチャンネルの後に「（記録無）」という文字をくっつけてしまったので、endswithの条件分岐でこのチャンネルが認識されないようになってしまった。なので、endswithからinを使って文字列に含むかどうかの条件式に変更

- before
```py
            elif channel.name.endswith("勉強机を作成"):
```
- after
```py
            elif "勉強机を作成" in channel.name:
```

**Comment by supleiades** [comment]
- 勉強机退出時にエラー発生
```py
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/centos/staging/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/staging/discord.CodeWarehouse/Cogs/Managements/create_studydesk.py", line 179, in on_voice_state_update
    if (after.channel.id in self.MOVECHANNELS and before.channel is None):
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by supleiades** [comment]
- 入室時
![image](https://user-images.githubusercontent.com/45380191/151199801-ba31520b-08e5-4fc3-bb39-4568b07b6e0f.png)
- 退出時
![image](https://user-images.githubusercontent.com/45380191/151199926-84625925-1d02-493f-91dd-340a47fc3c0f.png)

**Comment by supleiades** [comment]
```py

Ignoring exception in command studydesk_posreset:
Traceback (most recent call last):
  File "/home/centos/staging/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/centos/staging/discord.CodeWarehouse/Cogs/Managements/create_studydesk.py", line 193, in studydesk_posreset
    await self.boolif_runedit()
  File "/home/centos/staging/discord.CodeWarehouse/Cogs/Managements/create_studydesk.py", line 113, in boolif_runedit
    if self.check_pos():
  File "/home/centos/staging/discord.CodeWarehouse/Cogs/Managements/create_studydesk.py", line 97, in check_pos
    "NFKD", r_d.match(channel.name)[1])
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/centos/staging/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/centos/staging/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/centos/staging/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not subscriptable
```
