### ISSUE TITLE
[既存機能のエラー]ピン留め機能

### ISSUE THREAD

**Issue by su-pleiades** [mo9mo9study/discord.CodeWarehouse#47]
- 自分のtimesのメッセージはピン留めできる
- 自分のtimes以外のメッセージがピン留めできてない

# エラー
```py
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/PersonalPin.py", line 23, in on_raw_reaction_add
    embed.add_field(name=WordCount(message.content),value=f"[URL](https://discord.com/channels/{payload.member.guild.id}/{ChannelID}/{MessageID})")
NameError: name 'WordCount' is not defined
```

**Comment by su-pleiades** [comment]
失敗しているピン留め
```
790182485492760606
<Message id=790182485492760606 channel=<TextChannel id=603582455756095490 name='フリーチャット' position=0 nsfw=False news=False category_id=None> type=<MessageType.default: 0> author=<Member id=521479055841689611 name='nin' discriminator='2351' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=98>> flags=<MessageFlags value=0>>
```

成功しているピン留め
```
792003936004603954
<Message id=792003936004603954 channel=<TextChannel id=673006702924136448 name='times_supleiades' position=32 nsfw=False news=False category_id=709805664163332147> type=<MessageType.default: 0> author=<Member id=603567991132782592 name='SuPleiades' discriminator='7704' bot=False nick=None guild=<Guild id=603582455756095488 name='もくもくOnline勉強会' shard_id=None chunked=True member_count=98>> flags=<MessageFlags value=0>>
```

**Comment by su-pleiades** [comment]
上記問題は同じクラス内から別の関数を呼ぶ時に、seldの引数がなかったため、WordCountなんて関数はないと言われていた
本来ならself.WordCountとなる所だった。
というわけで、一旦動作はした

**Comment by su-pleiades** [comment]
新たなエラーを確認
```
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/work/discord.CodeWarehouse/python/Cogs/Managements/PersonalPin.py", line 30, in on_raw_reaction_add
    await ctx.message.pin()
NameError: name 'ctx' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/centos/work/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/work/discord.CodeWarehouse/python/Cogs/Managements/PersonalPin.py", line 32, in on_raw_reaction_add
    await ctx.send("pin数が上限に達しました。")
NameError: name 'ctx' is not defined
```
