### ISSUE TITLE
view_TimesChannel追加後のエラー

### ISSUE THREAD

**Issue by su-pleiades** [mo9mo9study/discord.CodeWarehouse#49]
```py
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/view_TimesChannel.py", line 39, in on_raw_reaction_add
    await self.time_sleep(msg, payload)
TypeError: time_sleep() takes 2 positional arguments but 3 were given
```

**Comment by su-pleiades** [comment]
- time_sleep関数に不要な引数を削除
- メッセージ削除メソッドを.purge()に変更

**Comment by su-pleiades** [comment]
```py
/home/centos/work/discord.CodeWarehouse/python/Cogs/Managements/view_TimesChannel.py:17: RuntimeWarning: coroutine 'TextChannel.purge' was never awaited
  self.select_channel.purge()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by su-pleiades** [comment]
channelをtimes_channel
select_channelをchannel
に文字列を変更する
