### ISSUE TITLE
join_leave_log/参加ログが表示されない問題について

### ISSUE THREAD

**Issue by su-pleiades** [mo9mo9study/discord.CodeWarehouse#5]
# 対象ファイル
- https://github.com/mo9mo9study/discord.CodeWarehouse/blob/master/node/join_leave_log.js
# エラー内容
```js
      name: 'もくもくOnline勉強会',
      icon: '9b5f42d9dda27d1483ffe01386833d13',
      splash: 'e055463ad7088d5c9fa889448ae6ad64',
      discoverySplash: null,
      region: 'hongkong',
      memberCount: 87,
      large: true,
      features: [Array],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: '685490377754804278',
      embedEnabled: undefined,
      premiumTier: 1,
      premiumSubscriptionCount: 4,
      verificationLevel: 'LOW',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1588947018621,
      defaultMessageNotifications: 'MENTIONS',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 250000,
      vanityURLCode: null,
      vanityURLUses: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      preferredLocale: 'en-US',
      ownerID: '603567991132782592',
      emojis: [GuildEmojiManager]
    },
    messages: MessageManager {
      cacheType: [Function: LimitedCollection],
      cache: [LimitedCollection [Map]],
      channel: [Circular]
    },
    _typing: Map {}
  },
  createdTimestamp: 1604440608538
}
(node:4635) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
    at /home/centos/repos/discord.CodeWarehouse/node/join_leave_log.js:41:101
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4635) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by su-pleiades** [comment]
[問題の入口](https://mo9mo9study.github.io/discord.web/)
このサイトに埋め込まれている
Discordの右下にあるconnectから
ギルドに参加出来る
![image](https://user-images.githubusercontent.com/45380191/98183114-ccdcde80-1f4a-11eb-8929-ef38e5274548.jpeg)

- ここから参加出来るのは問題ない
# 問題
招待リンクの場合誰経由で参加したことを記録するBOTは正常に動くが、この入口経由の場合、メンバーが作ったものではなく必要なパラメータが含まれていないためエラーになり参加ログが残らない

# 解決方法
- 一般的な招待Urlからの参加と今回の入口からの参加方法でどの様な処理の違いがあるか特定
- 既存コードの前に、今回の入口からの処理を加えてる

**Comment by su-pleiades** [comment]
その他APIの変更により、通常の招待URLの処理も実行されなくなっている
https://scrapbox.io/discordjs-japan/2020%E5%B9%B410%E6%9C%887%E6%97%A5%E3%81%AEDiscord_API%E3%81%AE%E4%BB%95%E6%A7%98%E5%A4%89%E6%9B%B4

APIの仕様変更の影響と思われるので、BOT側で設定が必要になる（デベロッパーツール）

**Comment by su-pleiades** [comment]
設定項目についてはコチラ
- https://scrapbox.io/discordjs-japan/Developer_Portal%E3%81%8B%E3%82%89Privileged_Intents%E3%82%92%E6%9C%89%E5%8A%B9%E5%8C%96%E3%81%99%E3%82%8B

**Comment by su-pleiades** [comment]
- cronBOTの設定を変更
![image](https://user-images.githubusercontent.com/45380191/98448529-f6c31a80-216f-11eb-88a0-d611623fbe9e.png)

**Comment by su-pleiades** [comment]
招待コードでの参加時は実行を確認

**Comment by su-pleiades** [comment]
ウェブからのギルド参加の動作は未確認なので、
次参加する人がいればあえてギルドのウェブから
参加してもらうよう促して実験する。

**Comment by su-pleiades** [comment]
このエラーを確認
```
(node:3227) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
    at /home/centos/repos/discord.CodeWarehouse/node/join_leave_log.js:42:24
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3227) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by su-pleiades** [comment]
ウィジェット経由でギルドに参加する入り口を削除したため、
以降この問題は出ないと思われるのでクローズ
