### ISSUE TITLE
rolesmanagerでリアクション押しても権限が付与されない

### ISSUE THREAD

**Issue by su-pleiades** [mo9mo9study/discord.CodeWarehouse#51]
- リアクション押しても、「〜付与しました」みたいなメッセージが流れない
# エラー
```py
Ignoring exception in on_raw_reaction_remove
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/rolesmanager.py", line 53, in on_raw_reaction_remove
    if payload.message_id == self.message_id:
AttributeError: 'Reaction_AddRole' object has no attribute 'message_id'
```

**Comment by su-pleiades** [comment]
今Cogs化している、selfで呼び出している変数は他のCogs配下全てに影響を与えていると思われる
もしかすると、Aの処理とBの処理で同じself.~の同一変数名がある場合、どちらかが上書きされているかもしれない

**Comment by su-pleiades** [comment]
上は関係は関係ないです（（
変数名の記載ミス
ついでにRolesmanagetのリファクタリングしてpush・mergeする
