### ISSUE TITLE
勉強スロットが揃っても"勉強スロット当選者"チャンネルに投稿しないバグ

### ISSUE THREAD

**Issue by tako-eng** [mo9mo9study/discord.CodeWarehouse#75]
発生時期：2020/12/1以降？（最後の投稿がこの日）

当たったらちょっと嬉しいので、改修よろしくお願いしますmm

**Comment by su-pleiades** [comment]
# エラー
```py
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "slot_studyrecord.py", line 60, in on_message
    userMentionId = guildMembers[intCountLoop].mention
IndexError: list index out of range
```
