### ISSUE TITLE
自己紹介処理でBOTのメッセージに内容初期化のリアクションを押しても動作しない件

### ISSUE THREAD

**Issue by su-pleiades** [mo9mo9study/discord.CodeWarehouse#76]
# 問題
- メッセージの内容を部分的に修正するか、初期化して新たに自己紹介を作り直すかの大きく２パターンある
- その２パターンから後者の機能がエラー吐いている（前者は問題なさそう）
- 以下のリアクションを押した時
![image](https://user-images.githubusercontent.com/45380191/106061067-3fb7b900-6138-11eb-90c2-dbd69f8a912f.png)

# エラー内容
```py
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/selfIntroduction.py", line 105, in on_message
    selfintroduction_message = await self.INTRODUCTION_CHANNEL.fetch_message(int(messages[1].content))
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/abc.py", line 970, in fetch_message
    data = await self._state.http.get_message(channel.id, id)
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
```

**Comment by su-pleiades** [comment]
この上記エラーは開発時の情報を取得してエラーを吐いている
# 解説
- 自己紹介を投稿したメッセージIDを取得して保存してあり、そのIDを検索しに行ってメッセージのコンテンツを削除したりする
- しかし、保管されていたメッセージが見つからないと言われているが、
- 検証時はtimesに送信されていたメッセージのため、本番で想定される自己紹介チャンネルとは異なる場所なのでIDから検索しても、該当のメッセージが取得・削除できないということになる

# 対策
- これは純粋に開発メンバーだけが起きる現象だと思われるので修正作業なしでクローズ
