### ISSUE TITLE
error 自己紹介処理の送信でエラーを起こして処理が停止する問題

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.CodeWarehouse#95]
- 自己紹介の処理が完了したのち、「よろしく」のスタンプが付与されずにmanagement.pyが停止した
```py
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/rolesmanager.py", line 37, in on_raw_reaction_add
    if payload.member.bot:
AttributeError: 'NoneType' object has no attribute 'bot'
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/view_TimesChannel.py", line 27, in on_raw_reaction_add
    if payload.member.bot:
AttributeError: 'NoneType' object has no attribute 'bot'
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/rolesmanager.py", line 37, in on_raw_reaction_add
    if payload.member.bot:
AttributeError: 'NoneType' object has no attribute 'bot'
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/view_TimesChannel.py", line 27, in on_raw_reaction_add
    if payload.member.bot:
AttributeError: 'NoneType' object has no attribute 'bot'
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/rolesmanager.py", line 37, in on_raw_reaction_add
    if payload.member.bot:
AttributeError: 'NoneType' object has no attribute 'bot'
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/view_TimesChannel.py", line 27, in on_raw_reaction_add
    if payload.member.bot:
AttributeError: 'NoneType' object has no attribute 'bot'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/times.py", line 52, in on_message
    await self.channelCreateSend(self.getMember(user_id))
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/times.py", line 78, in channelCreateSend
    count = self.getChannelCount() #timesチャンネルの総数を取得
TypeError: getChannelCount() missing 1 required positional argument: 'which'
```

**Comment by supleiades** [comment]
これらエラーを解決したため、クローズ
https://github.com/mo9mo9study/discord.CodeWarehouse/pull/127
