### ISSUE TITLE
お遊び機能の勉強スロット処理で正規表現から情報取得できない問題

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.CodeWarehouse#97]
```py
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/centos/repos/discord.CodeWarehouse/python/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/repos/discord.CodeWarehouse/python/Cogs/Managements/slotstudyrecord.py", line 44, in on_message
    strName = strName[1]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by supleiades** [comment]
- 問題
![image](https://user-images.githubusercontent.com/45380191/136867324-4c8c6474-366d-4bb8-9957-fd624163f3c0.png)
